version: 1.0.{build}
image: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - npm test

build: off
